//
//  FoodListViewController.swift
//  VeganFuel
//
//  Created by Dierta Pasific on 01/12/23.
//

import UIKit

class FoodListViewController: UIViewController {
    
    @IBOutlet weak var categoryImageView: UIImageView!
    @IBOutlet weak var tableView: UITableView!
    
    var category: DishCategory!
    var foods: [Foods] = []
    
    override func viewDidLoad() {
        super.viewDidLoad()

        if(category.name == "Noodles"){
            categoryImageView.image = UIImage(named:"noodleImage")
           foods = [
                .init(id: "id1", name: "Chow Mein", image: "chowMien", calories: 300, description: "• 8 oz chow mein noodles\n• 2 tbsp vegetable oil\n• 1 onion, sliced\n• 2 bell peppers, julienned\n• 2 carrots, julienned\n •1 cup snow peas, trimmed\n• 1 cup mushrooms, sliced\n• 3 cloves garlic, minced\n• 1 tbsp ginger, grated\n• 1/4 cup soy sauce\n• 2 tbsp hoisin sauce\n• 1 tbsp rice vinegar\n• 1 tbsp maple syrup\n• Sesame oil, for drizzling\n• Green onions, chopped (for garnish)\n• Sesame seeds (for garnish)", price: "IDR 55.000", ratingImage: "fourRating"),
                .init(id: "id2", name: "Coconut Curry Bowl", image: "coconutCurry", calories: 550, description: "• 1 can Coconut milk\n• 1 can Chickpeas\n• Mixed vegetables (bell peppers, carrots, peas)\n• 200g Tofu\n• 2 tablespoons Red curry paste\n• 1 tablespoon Ginger\n• 3 cloves Garlic\n• 2 tablespoons Soy sauce\n• 1 tablespoon Lime juice\n• 1 tablespoon Brown sugar\n• 1 teaspoon Turmeric powder\n• 1 teaspoon Cumin powder\n• 1 teaspoon Coriander powder\n• 2 tablespoons Coconut oil\n• Fresh cilantro", price: "IDR 45.000", ratingImage: "fourRating"),
                .init(id: "id3", name: "Golden Broccoli", image: "goldenBroccoli", calories: 400, description: "• 1 lb fresh broccoli florets\n• 2 tbsp olive oil\n• 1 tsp turmeric powder\n• 2 tbsp nutritional yeast\n• 1 tsp garlic powder\n• 1 tsp onion powder\n• 1 tbsp Dijon mustard\n• 2 tbsp maple syrup\n• 2 tbsp tamari or soy sauce\n• 1 tbsp lemon juice\n• Salt & black pepper to taste\n• 1/2 cup almond flour\n• 3 tbsp vegan mayonnaise\n• 1/4 cup diced shallots\n", price: "IDR 50.000", ratingImage: "threeRating"),
                .init(id: "id4", name: "Sticky Tofu Noodles", image: "stickyTofu", calories: 970, description: "• 1 block of Tofu\n• 8 oz Rice noodles\n• 1/4 cup Soy sauce\n• 2 tbsp Maple syrup\n• 1 tbsp Sesame oil\n• 2 tbsp Rice vinegar\n• 2 tbsp Cornstarch\n• 3 cloves Garlic (minced)\n• 1 tbsp Ginger (minced)\n• 1/2 tsp Red pepper flakes\n• 4 Green onions (sliced)\n• 1 cup Carrots (julienned)\n• 1 cup Broccoli florets\n• 1 tbsp Sesame seeds\n• 2 cups Vegetable broth", price: "IDR 70.000", ratingImage: "fiveRating"),
                .init(id: "id5", name: "Satay Soup", image: "sataySoup", calories: 700, description: "• 1 can Coconut milk\n• 4 cups Vegetable broth\n• 1/2 cup Peanut butter\n• 1 block Tofu, cubed\n• 3 tbsp Soy sauce\n• 2 tbsp Lime juice\n• 3 cloves Garlic, minced\n• 1 tbsp Ginger, grated\n• 2 tbsp Red curry paste\n• 1 tsp Turmeric\n• 2 tbsp Brown sugar\n• 8 oz Rice noodles\n• 2 Carrots, julienned\n• 1 Red bell pepper, sliced\n• 4 Green onions, chopped", price: "IDR 75.000", ratingImage: "fourRating"),
                .init(id: "id6", name: "Yaki Udon", image: "yakiUdon", calories: 350, description: "• Udon noodles (200g)\n• Soy sauce (3 tbsp)\n• Mirin (2 tbsp)\n• Sesame oil (1 tbsp)\n• Maple syrup (1 tbsp)\n• Garlic, minced (2 cloves)\n• Ginger, grated (1 tbsp)\n• Shiitake mushrooms, sliced (1 cup)\n• Carrot, julienned (1 large)\n• Red bell pepper, sliced (1 medium)\n• Bok choy, chopped (2 cups)\n• Scallions, chopped (1/2 cup)\n• Bean sprouts (1 cup)\n• Sesame seeds (1 tbsp)\n• Vegetable oil (2 tbsp)", price: "IDR 65.000", ratingImage: "twoRating"),
                .init(id: "id7", name: "Thai Curry", image: "thaiCurry", calories: 950, description: "• 1 can Coconut milk\n• 2-3 tablespoons Red curry paste\n• 1 block Tofu, cubed\n• Mixed vegetables (bell peppers, carrots, broccoli)\n• Thai basil leaves\n• 2 tablespoons Soy sauce\n• 1-2 tablespoons Brown sugar\n• Lime juice from 1 lime\n• 3 cloves Garlic, minced\n• 1 tablespoon Ginger, grated\n• 1 stalk Lemongrass, chopped\n• 1 Red chili, sliced\n• Salt to taste\n• 2 tablespoons Vegetable oil\n• Cooked rice", price: "IDR 55.000", ratingImage: "fiveRating"),
                .init(id: "id8", name: "Miso Ramen", image: "misoRamen", calories: 380, description: "• Vegan ramen noodles\n• 3 tablespoons miso paste\n• 4 cups vegetable broth\n• 2 tablespoons soy sauce\n• 1 tablespoon sesame oil\n• 3 cloves garlic, minced\n• 1 tablespoon ginger, grated\n• 1 cup shiitake mushrooms, sliced\n• 2 cups bok choy, chopped\n• 1 cup carrots, julienned\n• 4 green onions, sliced\n• 1 cup tofu, cubed\n• 2 nori sheets\n• Sriracha sauce to taste\n• Sesame seeds for garnish", price: "IDR 55.000", ratingImage: "threeRating"),
                .init(id: "id9", name: "Pad Thai", image: "padThai", calories: 330, description: "• Rice noodles (8 oz)\n• Tofu (1 block, pressed and cubed)\n• Bean sprouts (1 cup)\n• Carrots (2, julienned)\n• Bell peppers (1, thinly sliced)\n• Green onions (4, chopped)\n• Garlic (3 cloves, minced)\n• Peanut oil (2 tablespoons)\n• Soy sauce (3 tablespoons)\n• Lime (1, juiced)\n• Sriracha (1 tablespoon)\n• Agave syrup (2 tablespoons)\n• Peanuts (1/4 cup, chopped)\n• Cilantro (1/4 cup, chopped)\n• Sesame seeds (1 tablespoon)", price: "IDR 45.000", ratingImage: "fourRating")
            ]
        } else if(category.name == "Snacks"){
            categoryImageView.image = UIImage(named:"snackImage")
            foods = [
                 .init(id: "id1", name: "French Fries", image: "frenchFries", calories: 300, description: "• 4 large potatoes\n• 3 tablespoons olive oil\n• 1 teaspoon salt\n• 1/2 teaspoon pepper\n• 1/2 teaspoon garlic powder\n• 1/2 teaspoon onion powder\n• 1/2 teaspoon paprika\n• 2 tablespoons cornstarch\n• 1/2 teaspoon dried thyme\n• 1/2 teaspoon dried rosemary\n• 1/2 teaspoon smoked paprika\n• 1/4 cup vegan mayonnaise\n• 1/4 cup ketchup\n• 1 tablespoon Dijon mustard\n• Fresh parsley (for garnish)", price: "IDR 25.000", ratingImage: "fiveRating"),
                 .init(id: "id2", name: "Popcorn", image: "popcorn", calories: 85, description: "• Popcorn kernels\n• 1/2 cup Coconut oil\n• 1/4 cup Nutritional yeast\n• 2 tbsp Garlic powder\n• 1 tbsp Onion powder\n• 1 tsp Smoked paprika\n• 1/2 tsp Turmeric\n• 1/2 tsp Sea salt\n• 2 tbsp Maple syrup\n• 3 tbsp Vegan butter\n• 1 tbsp Dried dill\n• 1 tsp Lemon zest\n• 1/4 tsp Cayenne pepper\n• 1/2 cup Cashews\n• 2 tbsp Popcorn seasoning (vegan)", price: "IDR 15.000", ratingImage: "fourRating"),
                 .init(id: "id3", name: "Vegan Yogurt", image: "veganYogurt", calories: 150, description: "• 2 cups of coconut milk\n• 1 tablespoon of agar-agar powder\n• 2 tablespoons of tapioca starch\n• 2 tablespoons of maple syrup\n• 1 teaspoon of vanilla extract\n• 1 tablespoon of lemon juice\n• 1 probiotic capsule (opened)\n• 1/4 cup of raw cashews (soaked)\n• 1 tablespoon of nutritional yeast\n• 1/4 teaspoon of turmeric powder\n• Pinch of salt\n• Fresh fruit for topping (e.g., berries, mango)\n• 1 tablespoon of chia seeds\n• 1 tablespoon of shredded coconut\n• 1 tablespoon of chopped nuts", price: "IDR 25.000", ratingImage: "threeRating"),
                 .init(id: "id4", name: "Cassava Chips", image: "cassavaChips", calories: 150, description: "• 3 large cassava roots\n• 3 tablespoons olive oil\n• 1 teaspoon sea salt\n• 1 teaspoon garlic powder\n• 1 teaspoon onion powder\n• 1 teaspoon smoked paprika\n• 1/2 teaspoon ground black pepper\n• 2 tablespoons nutritional yeast\n• 1/2 teaspoon cumin powder\n• 1/2 teaspoon chili powder\n• 1/2 teaspoon turmeric powder\n• 1 tablespoon lemon juice\n• 2 tablespoons fresh parsley (chopped)\n• Avocado (optional, for serving)\n• Vegan mayo (optional, for dipping)", price: "IDR 25.000", ratingImage: "fourRating"),
                 .init(id: "id5", name: "Seaweed Chips", image: "seaweedChips", calories: 50, description: "• 2 packs of Seaweed sheets\n• 2 tablespoons of Olive oil\n• 2 tablespoons of Soy sauce\n• 1 tablespoon of Rice vinegar\n• 1 teaspoon of Sesame oil\n• 1 teaspoon of Agave syrup\n• 1/2 teaspoon of Garlic powder\n• 1/2 teaspoon of Onion powder\n• 1/2 teaspoon of Smoked paprika\n• 1 tablespoon of Sesame seeds\n• Salt (to taste)\n• Pepper (to taste)\n• 1 tablespoon of Nutritional yeast\n• 1/2 teaspoon of Cumin\n• Chili flakes (optional, to taste)", price: "IDR 10.000", ratingImage: "threeRating"),
                 .init(id: "id6", name: "Mixed Nuts", image: "mixedNuts", calories: 200, description: "• 1 cup Almonds\n• 1/2 cup Walnuts\n• 1/2 cup Cashews\n• 1/2 cup Pecans\n• 1/4 cup Pistachios\n• 1/4 cup Hazelnuts\n• 1/4 cup Macadamia nuts\n• 1/4 cup Brazil nuts\n• 1/4 cup Pine nuts\n• 1/4 cup Sunflower seeds\n• 1/4 cup Pumpkin seeds\n• 1/4 cup Coconut flakes\n• 2 tablespoons Maple syrup\n• 1 tablespoon Coconut oil\n• Sea salt (to taste)", price: "IDR 35.000", ratingImage: "fourRating"),
                 .init(id: "id7", name: "Protein Balls", image: "proteinBalls", calories: 145, description: "• 1 cup Rolled oats\n• 1/2 cup Almond butter\n• 2 tbsp Flaxseeds\n• 1 tbsp Chia seeds\n• 1/4 cup Maple syrup\n• 1 tsp Vanilla extract\n• 1/4 cup Coconut flakes\n• 1/2 cup Plant-based protein powder\n• 1 tsp Cinnamon\n• 1/3 cup Dark chocolate chips\n• 1/2 cup Dates, chopped\n• 2-3 tbsp Almond milk\n• 2 tbsp Hemp seeds\n• 1/2 cup Shredded carrots\n• 1/4 cup Pecans, chopped", price: "IDR 25.000", ratingImage: "fiveRating"),
                 .init(id: "id8", name: "Chickpea Panisse", image: "chickpeaPanisse", calories: 165, description: "• 1 cup Chickpea flour\n• 1 1/4 cups Water\n• 2 tablespoons Olive oil\n• 1 teaspoon Garlic powder\n• 1 teaspoon Onion powder\n• 1/2 teaspoon Paprika\n• 1/2 teaspoon Turmeric\n• 1 teaspoon Salt\n• 1/2 teaspoon Black pepper\n• 1 tablespoon Lemon juice\n• 2 tablespoons Fresh parsley, chopped\n• 2 tablespoons Tahini\n• 1/2 teaspoon Cumin\n• 1/2 teaspoon Baking powder\n• 2 cups Vegetable oil (for frying)", price: "IDR 35.000", ratingImage: "twoRating"),
                 .init(id: "id9", name: "Orange Lollies", image: "orangeLollies", calories: 75, description: "• 2 cups fresh orange juice\n• 1 cup coconut milk\n• 1/4 cup agave syrup\n• 1 teaspoon vanilla extract\n• Zest of 1 orange\n• 1 tablespoon arrowroot powder\n• Popsicle molds\n• 1/4 cup dried coconut flakes\n• 2 tablespoons maple syrup\n• 1 packet vegan orange-flavored gelatin\n• 1 cup water\n• 1/2 teaspoon orange extract\n• Pinch of salt\n• Fresh oranges (for garnish)\n• Popsicle sticks", price: "IDR 15.000", ratingImage: "oneRating")
             ]
         } else if(category.name == "Salads"){
             categoryImageView.image = UIImage(named:"saladImage")
             foods = [
                  .init(id: "id1", name: "Allotment Salad", image: "allotmentSalad", calories: 125, description: "• 4 cups mixed salad greens\n• 1 cup cherry tomatoes, halved\n• 1 cucumber, sliced\n• 1 avocado, diced\n• 1 cup radishes, thinly sliced\n• 1 red bell pepper, chopped\n• 2 carrots, shredded\n• 1/2 red onion, thinly sliced\n• 1 cup cooked quinoa\n• 1 can (15 oz) chickpeas, drained and rinsed\n• 1/4 cup sunflower seeds\n• 1/4 cup fresh basil, chopped\n• 1/4 cup lemon vinaigrette dressing\n• 2 tablespoons olive oil\n• Salt and pepper to taste\n", price: "IDR 35.000", ratingImage: "threeRating"),
                  .init(id: "id2", name: "Winter Salad", image: "winterSalad", calories: 450, description: "• 6 cups mixed winter greens\n• 2 cups roasted sweet potatoes\n• 1 cup pomegranate seeds\n• 1/2 cup sliced almonds\n• 1 avocado, diced\n• 1 cup shredded Brussels sprouts\n• 1 cup cooked quinoa\n• 1/2 cup dried cranberries\n• 1/2 cup sliced radishes\n• 1/4 cup maple Dijon vinaigrette\n• 3 tablespoons olive oil\n• 2 tablespoons balsamic vinegar\n• Salt, to taste\n• Pepper, to taste\n• 2 tablespoons maple syrup", price: "IDR 45.000", ratingImage: "fourRating"),
                  .init(id: "id3", name: "Kisir Salad", image: "kisirSalad", calories: 375, description: "• 1 cup Bulgur wheat\n• 2 Tomatoes, diced\n• 1 Cucumber, diced\n• 1 Red bell pepper, diced\n• 4 Green onions, finely chopped\n• 1/2 cup Fresh parsley, chopped\n• 1/4 cup Fresh mint, chopped\n• 1/4 cup Olive oil\n• 2 tablespoons Pomegranate molasses\n• Juice of 1 Lemon\n• 2 cloves Garlic, minced\n• 1 teaspoon Ground cumin\n• 1/2 teaspoon Ground coriander\n• Salt (to taste)\n• Black pepper (to taste)", price: "IDR 55.000", ratingImage: "fiveRating"),
                  .init(id: "id4", name: "Chickpea Salad", image: "chickpeaSalad", calories: 125, description: "• 2 cans Chickpeas\n• 1 cup Cherry tomatoes\n• 1 Cucumber\n• 1/2 Red onion\n• 1 Bell pepper\n• 1/4 cup Fresh parsley\n• 3 tablespoons Olive oil\n• 2 tablespoons Lemon juice\n• 1 tablespoon Dijon mustard\n• 2 cloves Garlic\n• Salt to taste\n• Pepper to taste\n• 1 teaspoon Cumin\n• 1 teaspoon Paprika\n• 1 Avocado", price: "IDR 45.000", ratingImage: "threeRating"),
                  .init(id: "id5", name: "Celery Salad", image: "celerySalad", calories: 235, description: "• Celery (2 cups, chopped)\n• Cherry tomatoes (1 cup, halved)\n• Cucumber (1, diced)\n• Red onion (1/2 cup, thinly sliced)\n• Avocado (1, diced)\n• Fresh parsley (1/4 cup, chopped)\n• Olive oil (2 tablespoons)\n• Lemon juice (2 tablespoons)\n• Dijon mustard (1 teaspoon)\n• Maple syrup (1 teaspoon)\n• Salt (1/2 teaspoon)\n• Pepper (1/4 teaspoon)\n• Garlic powder (1/2 teaspoon)\n• Almonds (1/4 cup, sliced)\n• Quinoa (1 cup, cooked)", price: "IDR 35.000", ratingImage: "threeRating"),
                  .init(id: "id6", name: "Hummus Pasta Salad", image: "hummusPastaSalad", calories: 400, description: "• Hummus (1 cup)\n• Pasta (8 oz)\n• Cherry tomatoes (1 cup, halved)\n• Cucumber (1, diced)\n• Red bell pepper (1, diced)\n• Red onion (1/2, finely chopped)\n• Kalamata olives (1/2 cup, sliced)\n• Fresh parsley (1/4 cup, chopped)\n• Lemon juice (2 tablespoons)\n• Olive oil (3 tablespoons)\n• Garlic (2 cloves, minced)\n• Salt (to taste)\n• Black pepper (to taste)\n• Red pepper flakes (optional, to taste)\n• Vegan feta cheese (1/2 cup, crumbled)", price: "IDR 65.000", ratingImage: "twoRating"),
                  .init(id: "id7", name: "Peanut Lime Salad", image: "peanutLimeSalad", calories: 375, description: "• Mixed salad greens (4 cups)\n• Cherry tomatoes (1 cup)\n• Cucumber, sliced (1 medium)\n• Red bell pepper, diced (1 medium)\n• Carrots, shredded (1 cup)\n• Red onion, thinly sliced (1/2 cup)\n• Avocado, diced (1 large)\n• Roasted peanuts (1/2 cup)\n• Fresh cilantro, chopped (1/4 cup)\n• Sesame seeds (1 tablespoon)\n• Lime juice (2 tablespoons)\n• Peanut butter (3 tablespoons)\n• Soy sauce (2 tablespoons)\n• Maple syrup (1 tablespoon)\n• Olive oil (2 tablespoons)\n", price: "IDR 55.000", ratingImage: "threeRating")
                  ]
          }  else if(category.name == "Cakes"){
              categoryImageView.image = UIImage(named:"cakeImage")
              foods = [
                   .init(id: "id1", name: "Lemon Cake", image: "lemonCake", calories: 265, description: "• 2 cups all-purpose flour\n• 1 cup sugar\n• 1 teaspoon baking soda\n• 1/2 teaspoon salt\n• 1 cup non-dairy milk\n• 1/2 cup vegetable oil\n• 1/4 cup fresh lemon juice\n• 2 tablespoons lemon zest\n• 1 teaspoon vanilla extract\n• 1 tablespoon apple cider vinegar\n• 1 cup powdered sugar\n• 2 tablespoons vegan butter, melted\n• 1 tablespoon non-dairy milk\n• 1 teaspoon lemon zest\n• 1 tablespoon lemon juice", price: "IDR 35.000", ratingImage: "fiveRating"),
                   .init(id: "id2", name: "Chocolate Cake", image: "chocolateCake", calories: 600, description: "• 2 cups all-purpose flour\n• 1 1/2 cups granulated sugar\n• 1/2 cup cocoa powder\n• 1 1/2 teaspoons baking powder\n• 1 1/2 teaspoons baking soda\n• 1 teaspoon salt\n• 1 3/4 cups non-dairy milk (e.g., almond, soy)\n• 1/2 cup vegetable oil\n• 2 tablespoons apple cider vinegar\n• 2 teaspoons vanilla extract\n• 1 cup boiling water\n• Vegan chocolate chips (optional)\n• Vegan frosting of choice\n• Fresh berries for garnish\n• Powdered sugar for dusting (optional)", price: "IDR 55.000", ratingImage: "fourRating"),
                   .init(id: "id3", name: "Carrot Cake", image: "carrotCake", calories: 500, description: "• 2 cups shredded carrots\n• 1 1/2 cups all-purpose flour\n• 1 cup granulated sugar\n• 1/2 cup vegetable oil\n• 1/4 cup unsweetened applesauce\n• 1 teaspoon baking powder\n• 1/2 teaspoon baking soda\n• 1/2 teaspoon ground cinnamon\n• 1/4 teaspoon ground nutmeg\n• 1/4 teaspoon salt\n• 1/2 cup chopped walnuts\n• 1/2 cup raisins\n• 1 teaspoon vanilla extract\n• 1 tablespoon apple cider vinegar\n• Vegan cream cheese frosting (store-bought or homemade)", price: "IDR 65.000", ratingImage: "twoRating"),
                   .init(id: "id4", name: "Apple Cake", image: "appleCake", calories: 450, description: "• 2 cups all-purpose flour\n• 1 cup sugar\n• 1 teaspoon baking soda\n• 1/2 teaspoon salt\n• 1 teaspoon cinnamon\n• 1/2 teaspoon nutmeg\n• 1/2 cup vegetable oil\n• 1/2 cup unsweetened applesauce\n• 1/4 cup almond milk\n• 1 tablespoon apple cider vinegar\n• 2 teaspoons vanilla extract\n• 2 cups peeled and diced apples\n• 1/2 cup chopped walnuts\n• 1/4 cup raisins\n• Powdered sugar for dusting", price: "IDR 45.000", ratingImage: "threeRating"),
                   .init(id: "id5", name: "Simnel Cake", image: "simnelCake", calories: 550, description: "• 225g self-raising flour\n• 100g vegan margarine\n• 100g light brown sugar\n• 200g mixed dried fruit\n• 50g candied peel\n• 1 tsp mixed spice\n• 1 tsp ground cinnamon\n• 150ml plant-based milk\n• 1 tbsp apple cider vinegar\n• 1 tsp vanilla extract\n• 200g marzipan\n• Apricot jam\n• Icing sugar\n• Almond flakes\n• Vegan chocolate eggs", price: "IDR 75.000", ratingImage: "fiveRating"),
                   .init(id: "id6", name: "Berry Cream Cake", image: "berryCream", calories: 350, description: "• 2 cups vegan cake mix\n• 1 cup blueberries\n• 1 1/2 cups non-dairy milk\n• 1/2 cup vegan butter\n• 2 cups powdered sugar\n• 8 oz vegan cream cheese\n• 1 tablespoon lemon juice\n• 1 teaspoon vanilla extract\n• 2 tablespoons cornstarch\n• 1 teaspoon baking powder\n• 1/2 teaspoon baking soda\n• 1/4 teaspoon salt\n• 2 cups all-purpose flour\n• 1/2 cup maple syrup\n• 1 tablespoon apple cider vinegar\n", price: "IDR 55.000", ratingImage: "fourRating"),
                   .init(id: "id7", name: "Vegan Trifle", image: "veganTrifle", calories: 400, description: "• Vegan sponge cake (1 prepared, store-bought or homemade)\n• Mixed berries (2 cups)\n• Vegan vanilla custard (2 cups)\n• Coconut whipped cream (1 cup)\n• Agave syrup (1/4 cup)\n• Almond milk (1 cup)\n• Cornstarch (2 tablespoons)\n• Vanilla extract (1 teaspoon)\n• Almond extract (1/2 teaspoon)\n• Vegan cream cheese (1/2 cup)\n• Powdered sugar (1/2 cup)\n• Lemon juice (1 tablespoon)\n• Shredded coconut (1/2 cup)\n• Fresh mint leaves (for garnish)\n• Chopped nuts (e.g., almonds or pistachios, 1/4 cup)\n", price: "IDR 55.000", ratingImage: "threeRating"),
                   .init(id: "id8", name: "Vegan Tiramisu", image: "veganTiramisu", calories: 500, description: "• Vegan sponge cake\n• 1 cup brewed espresso, cooled\n• 1/4 cup maple syrup\n• 1/4 cup almond milk\n• 1 tablespoon instant coffee powder\n• 1 cup cashews, soaked and drained\n• 1/2 cup coconut cream\n• 1/4 cup maple syrup\n• 2 teaspoons vanilla extract\n• 1/4 cup coconut oil, melted\n• Cocoa powder for dusting\n• Vegan chocolate chips (optional)\n• Fresh berries for garnish\n• Mint leaves for garnish", price: "IDR 45.000", ratingImage: "fiveRating")
               ]
           } else if(category.name == "Pizzas"){
               categoryImageView.image = UIImage(named:"pizzaImage")
               foods = [
                    .init(id: "id1", name: "Margherita Pizza", image: "margPizza", calories: 700, description: "• 1 pizza dough\n• 1 cup tomato sauce\n• 1-2 cups vegan mozzarella cheese\n• 2 fresh tomatoes, sliced\n• Fresh basil leaves\n• 2 tablespoons olive oil\n• 1 teaspoon garlic powder\n• 1 teaspoon onion powder\n• 1 teaspoon oregano\n• Salt to taste\n• Black pepper to taste\n• Red pepper flakes to taste\n• Cornmeal (for dusting)\n• Balsamic glaze (drizzle as desired)\n• Vegan parmesan (optional, sprinkle as desired)", price: "IDR 75.000", ratingImage: "threeRating"),
                    .init(id: "id2", name: "White Pizza", image: "whitePizza", calories: 550, description: "• 1 pizza dough\n• 2 tablespoons olive oil\n• 3 garlic cloves, minced\n• 1 cup vegan ricotta cheese\n• 1 cup vegan mozzarella cheese, shredded\n• 1 cup spinach, chopped\n• 1/2 cup cherry tomatoes, sliced\n• 1/2 cup artichoke hearts, drained and chopped\n• 1/4 cup red onion, thinly sliced\n• Salt, to taste\n• Pepper, to taste\n• 2 tablespoons nutritional yeast\n• Fresh basil, for garnish\n• 1 tablespoon lemon juice\n• Crushed red pepper flakes, optional", price: "IDR 85.000", ratingImage: "fourRating"),
                    .init(id: "id3", name: "Courgette Pizzettes", image: "courgettePizza", calories: 500, description: "• Courgettes (2 medium-sized)\n• Vegan pizza sauce (1 cup)\n• Vegan cheese (1 cup, shredded)\n• Cherry tomatoes (1/2 cup, sliced)\n• Red onion (1/4 cup, thinly sliced)\n• Fresh basil (1/4 cup, chopped)\n• Olive oil (2 tablespoons)\n• Garlic powder (1 teaspoon)\n• Salt (1/2 teaspoon)\n• Pepper (1/4 teaspoon)\n• Balsamic glaze (2 tablespoons)\n• Vegan parmesan (2 tablespoons, grated)\n• Oregano (1 teaspoon, dried)\n• Whole wheat pizza dough (1 pound)\n• Cornmeal (for dusting)", price: "IDR 65.000", ratingImage: "threeRating"),
                    .init(id: "id4", name: "Pizza Rolls", image: "pizzaRolls", calories: 250, description: "• Pizza dough (1 pound)\n• Vegan pizza sauce (1 cup)\n• Vegan cheese (shredded, 1 to 1.5 cups)\n• Vegan pepperoni slices (1 cup)\n• Chopped bell peppers (1/2 cup)\n• Sliced black olives (1/4 cup)\n• Diced red onions (1/4 cup)\n• Minced garlic (2 cloves)\n• Olive oil (2 tablespoons)\n• Dried oregano (1 teaspoon)\n• Dried basil (1 teaspoon)\n• Garlic powder (1/2 teaspoon)\n• Onion powder (1/2 teaspoon)\n• Salt (to taste)\n• Non-dairy milk (for brushing, 2 tablespoons)", price: "IDR 45.000", ratingImage: "oneRating"),
                    .init(id: "id5", name: "Avocado Pizza Crisps", image: "avocadoPizza", calories: 550, description: "• Pizza dough (1 package)\n• Avocado (2, sliced)\n• Vegan cheese (1 cup, shredded)\n• Cherry tomatoes (1 cup, halved)\n• Red onion (1/2, thinly sliced)\n• Garlic cloves (2, minced)\n• Fresh basil (1/4 cup, chopped)\n• Olive oil (2 tablespoons)\n• Lemon juice (1 tablespoon)\n• Salt (to taste)\n• Black pepper (to taste)\n• Red pepper flakes (optional)\n• Balsamic glaze (2 tablespoons)\n• Arugula (1 cup)\n• Vegan parmesan (optional, for topping)", price: "IDR 55.000", ratingImage: "threeRating")
                ]
            } else if(category.name == "Beverages"){
                
                categoryImageView.image = UIImage(named:"beverageImage")
                foods = [
                     .init(id: "id1", name: "Strawberry Smoothie", image: "strawberrySmoothie", calories: 150, description: "• 1 cup fresh strawberries\n• 1 ripe banana\n• 1/2 cup plant-based yogurt\n• 1 cup almond milk\n• 1 tablespoon chia seeds\n• 1 tablespoon agave syrup\n• Handful of ice cubes\n• Handful of spinach leaves\n• 1 tablespoon flaxseed meal\n• 1 scoop vegan protein powder\n• 2 tablespoons coconut flakes\n• Few mint leaves\n• 1 tablespoon lemon juice\n• 1 tablespoon almond butter\n• 1/4 cucumber", price: "IDR 25.000", ratingImage: "fiveRating"),
                     .init(id: "id2", name: "Peanut Smoothie", image: "peanutSmoothie", calories: 200, description: "• 1 cup unsweetened almond milk\n• 2 ripe bananas\n• 1/4 cup natural peanut butter\n• 1 tablespoon chia seeds\n• 1 tablespoon flaxseeds\n• 1 tablespoon hemp seeds\n• 1 tablespoon agave syrup\n• 1/2 teaspoon vanilla extract\n• 1 cup ice cubes\n• 1/2 cup frozen strawberries\n• 1/2 cup spinach leaves\n• Pinch of sea salt\n• Optional: 1 tablespoon cacao nibs\n• Optional: 1 scoop vegan protein powder\n• Optional: 1/2 teaspoon cinnamon", price: "IDR 30.000", ratingImage: "fourRating"),
                     .init(id: "id3", name: "Strawberry Lemon", image: "strawberryLemonade", calories: 75, description: "• 2 cups fresh strawberries\n• 1 cup lemon juice\n• 1/2 cup sugar\n• 4 cups water\n• Ice cubes\n• 1/4 cup fresh mint leaves\n• 2 tablespoons agave syrup\n• 2 cups sparkling water\n• Lemon slices (for garnish)\n• Strawberry slices (for garnish)\n• 1 tablespoon cold-pressed coconut oil\n• 1/4 teaspoon sea salt\n• 1 tablespoon chia seeds\n• 1 cup coconut water\n• Crushed ice", price: "IDR 25.000", ratingImage: "threeRating"),
                     .init(id: "id4", name: "Peach Iced Tea", image: "peachTea", calories: 65, description: "• 4 fresh peaches\n• 4-6 black tea bags\n• 4 cups boiling water\n• 2-4 tablespoons agave syrup\n• 1-2 tablespoons lemon juice\n• 2 cups ice cubes\n• Fresh mint leaves (to taste)\n• Peach slices for garnish\n• 2 cups water\n• Additional ice cubes\n• Tea infuser or strainer\n• Lemon slices for garnish\n• Optional: 1/4 cup peach-flavored vegan syrup\n• Optional: A few dashes of peach bitters\n• Optional: Sparkling water (as desired)", price: "IDR 15.000", ratingImage: "fourRating"),
                     .init(id: "id5", name: "Passion Fruit Mule", image: "passionMule", calories: 345, description: "• 2 oz passion fruit juice\n• 1.5 oz vodka\n• 0.5 oz ginger syrup\n• 0.75 oz lime juice\n• 1 cup crushed ice\n• 4 oz ginger beer\n• Fresh mint leaves\n• Thin lime slices\n• 1/2 oz agave syrup\n• 1/4 tsp turmeric powder\n• Dash of black pepper\n• 1 oz apple cider vinegar\n• 1/2 oz orange liqueur\n• Passion fruit slices for garnish\n• 1/4 tsp cayenne pepper", price: "IDR 25.000", ratingImage: "oneRating"),
                     .init(id: "id6", name: "Hot Chocolate", image: "hotChocolate", calories: 145, description: "• 2 cups plant-based milk\n• 1/2 cup vegan chocolate chips\n• 2 tablespoons cocoa powder\n• 2 tablespoons maple syrup\n• 1 tablespoon agave nectar\n• 1 teaspoon vanilla extract\n• 1/2 teaspoon cinnamon\n• 1/4 teaspoon nutmeg\n• 1 tablespoon almond butter\n• 1/4 cup coconut cream\n• Pinch of sea salt\n• 1 teaspoon cornstarch\n• Plant-based whipped cream (to taste)\n• Vegan marshmallows (to taste)\n• Optional: a few drops of peppermint extract (to taste)", price: "IDR 35.000", ratingImage: "fiveRating")
                 ]
             } else if(category.name == "Soups"){
                 categoryImageView.image = UIImage(named:"soupImage")
                 foods = [
                      .init(id: "id1", name: "Tomato Soup", image: "tomatoSoup", calories: 135, description: "• 4 cups tomatoes, diced\n• 1 onion, chopped\n• 3 cloves garlic, minced\n• 4 cups vegetable broth\n• 1 can (14 oz) diced tomatoes\n• 1/4 cup tomato paste\n• 1 teaspoon sugar\n• 1 teaspoon dried basil\n• 1 teaspoon dried oregano\n• Salt and pepper to taste\n• 1/2 cup cashews, soaked\n• 1/2 cup nutritional yeast\n• 1/4 cup fresh basil, chopped\n• 2 tablespoons olive oil\n• 1/2 cup coconut milk", price: "IDR 35.000", ratingImage: "twoRating"),
                      .init(id: "id2", name: "Watercress Soup", image: "watercressSoup", calories: 155, description: "• 2 bunches of Watercress\n• 2 medium-sized Potatoes\n• 1 large Onion\n• 3 cloves of Garlic\n• 4 cups Vegetable broth\n• 2 tablespoons Olive oil\n• Juice of 1 Lemon\n• Salt to taste\n• Pepper to taste\n• 2 tablespoons Nutritional yeast\n• 1 cup Coconut milk\n• Fresh parsley, chopped\n• 1 Avocado, sliced\n• Red pepper flakes to taste\n• Homemade or store-bought Croutons", price: "IDR 35.000", ratingImage: "oneRating"),
                      .init(id: "id3", name: "Broccoli Soup", image: "broccoliSoup", calories: 225, description: "• Broccoli (4 cups, chopped)\n• Onion (1 medium, chopped)\n• Garlic (3 cloves, minced)\n• Carrot (2 medium, diced)\n• Celery (2 stalks, diced)\n• Vegetable broth (4 cups)\n• Coconut milk (1 can, 13.5 oz)\n• Nutritional yeast (2 tablespoons)\n• Olive oil (2 tablespoons)\n• Salt (to taste)\n• Pepper (to taste)\n• Turmeric (1 teaspoon)\n• Cumin (1/2 teaspoon)\n• Red pepper flakes (1/4 teaspoon)\n• Lemon juice (1 tablespoon)\n", price: "IDR 35.000", ratingImage: "fourRating"),
                      .init(id: "id4", name: "Indian Chickpea", image: "indianChickpea", calories: 160, description: "• 2 cups Chickpeas\n• 4 cups Vegetable broth\n• 1 Onion\n• 3 cloves Garlic\n• 2 Tomatoes\n• 1 cup Carrots\n• 2 cups Spinach\n• 1 tsp Cumin\n• 1 tsp Coriander\n• 1/2 tsp Turmeric\n• 1 tsp Garam masala\n• 1/2 tsp Paprika\n• 2 Bay leaves\n• 2 tbsp Olive oil\n• Salt and pepper to taste", price: "IDR 35.000", ratingImage: "threeRating"),
                      .init(id: "id5", name: "Pumpkin Soup", image: "pumpkinSoup", calories: 255, description: "• 1 small Pumpkin\n• 4 cups Vegetable broth\n• 1 cup Coconut milk\n• 1 Onion\n• 3 cloves Garlic\n• 1 tablespoon Ginger\n• 2 Carrots\n• 2 stalks Celery\n• 2 tablespoons Olive oil\n• 1 tablespoon Maple syrup\n• 1 teaspoon Cumin\n• 1 teaspoon Coriander\n• 1/2 teaspoon Nutmeg\n• Salt to taste\n• Pepper to taste", price: "IDR 35.000", ratingImage: "threeRating"),
                      .init(id: "id6", name: "Roasted Parnsip", image: "roastedParnsip", calories: 235, description: "• 1 pound Parsnips\n• 2 tablespoons Olive oil\n• 2 tablespoons Maple syrup\n• 1 tablespoon Balsamic vinegar\n• 1 teaspoon Dijon mustard\n• 1 teaspoon Garlic powder\n• 1 teaspoon Onion powder\n• 1 teaspoon Paprika\n• 1 teaspoon Thyme\n• 1 teaspoon Rosemary\n• 1/2 teaspoon Salt\n• 1/4 teaspoon Black pepper\n• 1 tablespoon Lemon juice\n• 2 tablespoons Chopped fresh parsley\n• 1/4 cup Pomegranate seeds", price: "IDR 35.000", ratingImage: "twoRating")
                  ]
              }

        
        title = category.name
        registerCells()
    }
    
    private func registerCells(){
        tableView.register(UINib(nibName: "FoodListTableViewCell", bundle: nil), forCellReuseIdentifier: "FoodListTableViewCell")
        
    }
    
}


extension FoodListViewController: UITableViewDelegate, UITableViewDataSource{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return foods.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "FoodListTableViewCell") as! FoodListTableViewCell
        cell.setup(food: foods[indexPath.row])
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let controller = FoodDetailViewController.instantiate()
        controller.food = foods[indexPath.row]
        tableView.cellForRow(at: indexPath)?.selectionStyle = .none
        navigationController?.pushViewController(controller, animated: true)
    }
}
